### PR TITLE
Update for 5 years worth of commits

### PR DESCRIPTION
**Pull request by MichaelNeas**
There has been over 1000 commits since we originally pulled this project, this merge request gets us back up to date with latest.

### CODE REVIEW

**Comment by jschlieber** [comment]
Any news about this PR? Why is it still open?

**Comment by MichaelNeas** [comment]
The previous owner no longer works with GE :( I tried to contact the team in charge of ge github and they said we need permission from the owners of the repo we want to push to.... but he's gone!  They haven't gotten back to me since August 7

**Comment by mdwragg** [comment]
Hey @michaelneas, can you reopen - I’ll merge.

Sorry, I dont really know what this org is for TBH but I’m an owner so should’ve responded...

Sorry X a zillion

**Comment by mdwragg** [comment]
Ok, I reopened, NP

**Comment by MichaelNeas** [comment]
Haha wow, thanks @mdwragg! I'm not sure what the org is for either, I can help you out with this repo if you ever need it.

**Comment by mdwragg** [comment]
Cool, thanks!

**Pull request merged**
